# Generated by Django 4.0.4 on 2022-06-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_test_teststatement_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='totalTimeForTest',
            new_name='total_Time_For_Test',
        ),
    ]
