# Generated by Django 4.0.4 on 2022-06-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_totaltimefortest_test_total_time_for_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='option1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='option2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='option3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='option4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='statement',
            field=models.CharField(max_length=255),
        ),
    ]
