# Generated by Django 4.0.4 on 2022-06-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_teststatement_testoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='total_Time_For_Test',
        ),
        migrations.AddField(
            model_name='test',
            name='total_Time_for_Test_in_Minutes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
