# Generated by Django 4.0.4 on 2022-06-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_test_total_time_for_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststatement',
            name='option1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='option2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='option3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='option4',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
