# Generated by Django 4.0.4 on 2022-06-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_teststatement_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststatement',
            name='option1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='option2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='option3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teststatement',
            name='option4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TestAns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.CharField(max_length=5000)),
                ('QId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teststatement')),
                ('TestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.test')),
            ],
            options={
                'ordering': ['TestId'],
            },
        ),
    ]
