# Generated by Django 4.0.4 on 2022-08-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_teststatement_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='test',
            field=models.CharField(choices=[('Python', 'Python')], default='Python', max_length=255),
        ),
    ]
