# Generated by Django 4.0.4 on 2022-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_jobmodel_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststatement',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
