# Generated by Django 4.0.4 on 2022-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_teststatement_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststatement',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[(models.CharField(blank=True, max_length=255, null=True), models.CharField(blank=True, max_length=255, null=True)), ('{option2}', '{opiton2}'), ('{option3}', '{opiton3}'), ('{option4}', '{opiton4}')], max_length=255, null=True),
        ),
    ]
