# Generated by Django 4.0.4 on 2022-08-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_teststatement_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststatement',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Be careful while adding answer. It should match the option exacty', max_length=255, null=True),
        ),
    ]
