# Generated by Django 4.0.4 on 2022-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_teststatement_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='test',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='test',
            field=models.ManyToManyField(to='myapp.test'),
        ),
    ]
