# Generated by Django 4.0.4 on 2022-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_jobmodel_test_jobmodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='test',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='tests',
            field=models.ManyToManyField(related_name='jobs', to='myapp.test'),
        ),
    ]
