# Generated by Django 4.0.4 on 2022-08-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_testresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestResults',
            new_name='TestResult',
        ),
    ]
