# Generated by Django 4.0.4 on 2022-08-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rename_testresults_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='time_ended',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='time_started',
            field=models.DateTimeField(),
        ),
    ]
