# Generated by Django 4.0.4 on 2022-08-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_testresult_time_ended_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
