# Generated by Django 4.0.3 on 2022-10-20 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_testresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='organization',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='company_name',
            field=models.CharField(max_length=255, null='True'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=50, null='True'),
        ),
        migrations.CreateModel(
            name='Total_Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Applicants', models.IntegerField(null=True)),
                ('InProgress', models.IntegerField(null=True)),
                ('Completed', models.IntegerField(null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jobmodel')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.test')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobmodel')),
            ],
        ),
    ]
