# Generated by Django 4.0.3 on 2022-10-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_jobmodel_organization_user_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='organization',
        ),
    ]
