# Generated by Django 4.0.3 on 2022-10-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_jobmodel_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_applications',
            old_name='job',
            new_name='title',
        ),
    ]
